-- CI-only direct dependency fixture for the V3.6.4 migration.
-- This file is copied into the ephemeral runner's migration directory. It is
-- never part of production migration history and contains no production data.

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'trip_editor')),
  trip_id text not null default '',
  constraint admin_users_normalized_email_check check (
    email = lower(btrim(email)) and position('@' in email) > 1
  )
);

create unique index admin_users_one_role_per_trip_email
on public.admin_users (email, role, trip_id);

create or replace function public.tc_current_email()
returns text
language sql
stable
set search_path = ''
as $$
  select lower(coalesce(nullif((select auth.jwt()) ->> 'email', ''), ''));
$$;

create or replace function public.tc_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where email = public.tc_current_email() and role = 'super_admin'
  );
$$;

create or replace function public.tc_is_trip_editor(target_trip_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where email = public.tc_current_email()
      and role = 'trip_editor'
      and trip_id = target_trip_id
  );
$$;

create or replace function public.tc_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create table public.trips (
  id text primary key,
  title text not null,
  departure_date date not null,
  participants jsonb not null default '[]'::jsonb,
  currency_config jsonb not null default '{"code":"JPY","symbol":"￥"}'::jsonb,
  sidebar_config jsonb not null default '[]'::jsonb,
  content jsonb not null default '{}'::jsonb,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trips_touch_updated_at
before update on public.trips
for each row execute function public.tc_touch_updated_at();

alter table public.admin_users enable row level security;
alter table public.trips enable row level security;

create policy admin_users_select_policy
on public.admin_users for select to authenticated
using (
  email = public.tc_current_email()
  or public.tc_is_super_admin()
  or public.tc_is_trip_editor(trip_id)
);

create policy admin_users_write_policy
on public.admin_users for all to authenticated
using (public.tc_is_super_admin())
with check (public.tc_is_super_admin());

create policy trips_select_policy
on public.trips for select to anon, authenticated using (true);

create policy trips_insert_policy
on public.trips for insert to authenticated
with check (
  (select auth.uid()) is not null
  and (public.tc_is_super_admin() or public.tc_is_trip_editor(id))
);

create policy trips_update_policy
on public.trips for update to authenticated
using (public.tc_is_super_admin() or public.tc_is_trip_editor(id))
with check (public.tc_is_super_admin() or public.tc_is_trip_editor(id));

create policy trips_delete_policy
on public.trips for delete to authenticated
using (public.tc_is_super_admin());

revoke all on public.admin_users from public, anon, authenticated;
grant select, insert, update, delete on public.admin_users to authenticated;
grant usage, select on sequence public.admin_users_id_seq to authenticated;

revoke all on public.trips from public, anon, authenticated;
grant select on public.trips to anon, authenticated;
grant insert, update, delete on public.trips to authenticated;

revoke all on function public.tc_current_email() from public;
revoke all on function public.tc_is_super_admin() from public;
revoke all on function public.tc_is_trip_editor(text) from public;
grant execute on function public.tc_current_email() to authenticated;
grant execute on function public.tc_is_super_admin() to authenticated;
grant execute on function public.tc_is_trip_editor(text) to authenticated;

