-- CI/local-only direct dependency fixture for the V3.8.1 migration.
-- Copy this file into an ephemeral Supabase project's migration directory
-- before the V3.8.1 migration. It must never enter production history.

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to anon, authenticated;

create table public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'trip_editor')),
  trip_id text not null default '',
  constraint admin_users_normalized_email_check check (
    email = lower(btrim(email)) and position('@' in email) > 1
  ),
  unique (email, role, trip_id)
);

create table public.trips (
  id text primary key,
  title text not null,
  departure_date date not null,
  participants jsonb not null default '[]'::jsonb,
  currency_config jsonb not null default '{"code":"JPY","symbol":"￥"}'::jsonb,
  sidebar_config jsonb not null default '[]'::jsonb,
  content jsonb not null default '{}'::jsonb,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.checklists (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  scope text not null check (scope in ('shared', 'private')),
  owner_user_id uuid null references auth.users(id) on delete cascade,
  title text not null default '確認清單'
);

create table public.other_info_items (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  title text not null default '測試資訊'
);

create table public.exchange_purchases (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  client_item_id text not null unique
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  description text not null default '測試支出'
);

create index checklists_trip_id_idx on public.checklists (trip_id);
create index other_info_items_trip_id_idx on public.other_info_items (trip_id);
create index exchange_purchases_trip_id_idx on public.exchange_purchases (trip_id);
create index expenses_trip_id_idx on public.expenses (trip_id);

create table public.app_data_revision (
  singleton boolean primary key default true,
  revision bigint not null default 0,
  updated_at timestamptz not null default now(),
  source_client_id uuid null,
  constraint app_data_revision_singleton_check check (singleton),
  constraint app_data_revision_nonnegative_check check (revision >= 0)
);

insert into public.app_data_revision (singleton, revision) values (true, 0);
insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
) values (
  '00000000-0000-0000-0000-000000000000',
  '38138138-1381-4381-8381-381381381381',
  'authenticated',
  'authenticated',
  'v381-sql-super@example.invalid',
  '',
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{}'::jsonb,
  now(),
  now()
);
insert into public.admin_users (email, role, trip_id)
values ('v381-sql-super@example.invalid', 'super_admin', '');
insert into public.trips (id, title, departure_date, content) values
  ('free-travel-2026-01', '系統保留自由行', date '2026-01-01', '{"days":[1]}'::jsonb),
  ('group-tour-2026-10', '系統保留團體行', date '2026-10-01', '{"days":[1]}'::jsonb);

create or replace function private.tc_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where email = coalesce(nullif(auth.jwt() ->> 'email', ''), '')
      and role = 'super_admin'
  );
$$;

create or replace function public.tc_is_super_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select private.tc_is_super_admin();
$$;

create or replace function private.tc_request_source_client_id()
returns uuid
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  request_headers jsonb;
  raw_client_id text;
begin
  request_headers := nullif(current_setting('request.headers', true), '')::jsonb;
  raw_client_id := nullif(request_headers ->> 'x-travel-companion-client-id', '');
  return raw_client_id::uuid;
exception
  when others then return null;
end;
$$;

create or replace function private.tc_broadcast_trip_data_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_revision public.app_data_revision%rowtype;
  recipient record;
  removed_editor_email text;
begin
  update public.app_data_revision
  set revision = revision + 1,
      updated_at = clock_timestamp(),
      source_client_id = private.tc_request_source_client_id()
  where singleton
  returning * into strict next_revision;

  if tg_table_schema = 'public'
    and tg_table_name = 'admin_users'
    and tg_op in ('UPDATE', 'DELETE')
    and (to_jsonb(old) ->> 'role') = 'trip_editor'
  then
    removed_editor_email := lower(to_jsonb(old) ->> 'email');
  end if;

  for recipient in
    select distinct app_user.id
    from auth.users as app_user
    join public.admin_users as manager on manager.email = lower(app_user.email)
    where manager.role in ('super_admin', 'trip_editor')
    union
    select removed_user.id
    from auth.users as removed_user
    where removed_editor_email is not null
      and lower(removed_user.email) = removed_editor_email
  loop
    perform realtime.send(
      jsonb_build_object(
        'revision', next_revision.revision,
        'updated_at', next_revision.updated_at,
        'source_client_id', next_revision.source_client_id
      ),
      'revision_changed',
      'travel-companion:data-revision:' || recipient.id::text,
      true
    );
  end loop;

  return null;
end;
$$;

create trigger trips_broadcast_data_revision_insert
after insert on public.trips for each row
execute function private.tc_broadcast_trip_data_revision();
create trigger trips_broadcast_data_revision_update
after update on public.trips for each row
execute function private.tc_broadcast_trip_data_revision();
create trigger trips_broadcast_data_revision_delete
after delete on public.trips for each row
execute function private.tc_broadcast_trip_data_revision();
create trigger admin_users_broadcast_trip_editor_insert
after insert on public.admin_users for each row
when (new.role = 'trip_editor')
execute function private.tc_broadcast_trip_data_revision();
create trigger admin_users_broadcast_trip_editor_update
after update on public.admin_users for each row
when (old.role = 'trip_editor' or new.role = 'trip_editor')
execute function private.tc_broadcast_trip_data_revision();
create trigger admin_users_broadcast_trip_editor_delete
after delete on public.admin_users for each row
when (old.role = 'trip_editor')
execute function private.tc_broadcast_trip_data_revision();

alter table public.admin_users enable row level security;
alter table public.trips enable row level security;
alter table public.checklists enable row level security;
alter table public.other_info_items enable row level security;
alter table public.exchange_purchases enable row level security;
alter table public.expenses enable row level security;
alter table public.app_data_revision enable row level security;

create policy admin_users_select_policy on public.admin_users
for select to authenticated using (true);
create policy trips_select_policy on public.trips
for select to anon, authenticated using (true);
create policy trips_insert_policy on public.trips
for insert to authenticated
with check ((select auth.uid()) is not null and (select public.tc_is_super_admin()));
create policy trips_update_policy on public.trips
for update to authenticated
using ((select public.tc_is_super_admin()))
with check ((select public.tc_is_super_admin()));
create policy trips_delete_policy on public.trips
for delete to authenticated using ((select public.tc_is_super_admin()));
create policy app_data_revision_select_managers on public.app_data_revision
for select to authenticated using ((select public.tc_is_super_admin()));

create policy app_data_revision_receive_broadcast on realtime.messages
for select to authenticated
using (
  realtime.messages.extension = 'broadcast'
  and realtime.topic() =
    'travel-companion:data-revision:' || (select auth.uid())::text
  and exists (
    select 1 from public.admin_users as manager
    where manager.email = coalesce(nullif((select auth.jwt()) ->> 'email', ''), '')
      and manager.role in ('super_admin', 'trip_editor')
  )
);

revoke all on public.admin_users, public.trips, public.checklists,
  public.other_info_items, public.exchange_purchases, public.expenses,
  public.app_data_revision from public, anon, authenticated;
grant select on public.trips to anon, authenticated;
grant select, insert, update, delete on public.trips to authenticated;
grant select, insert, update, delete on public.trips to service_role;
grant select, insert, update, delete on public.admin_users to authenticated, service_role;
grant select, insert, update, delete on public.checklists, public.other_info_items,
  public.exchange_purchases, public.expenses to authenticated, service_role;
grant select on public.app_data_revision to authenticated;
grant usage, select on sequence public.admin_users_id_seq to authenticated, service_role;

revoke all on function private.tc_is_super_admin(),
  private.tc_request_source_client_id(),
  private.tc_broadcast_trip_data_revision() from public, anon, authenticated, service_role;
grant execute on function private.tc_is_super_admin() to anon, authenticated;
revoke all on function public.tc_is_super_admin() from public, anon;
grant execute on function public.tc_is_super_admin() to authenticated;
