-- CI/local-only dependencies for the isolated V3.9.0 Storage migration test.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'trip_editor')),
  trip_id text not null default ''
);

create table public.trips (
  id text primary key,
  title text not null,
  departure_date date not null,
  content jsonb not null default '{}'::jsonb
);

create or replace function public.tc_attachment_storage_scope(value text)
returns text
language sql
immutable
strict
set search_path = ''
as $$
  select 's_' || encode(convert_to(value, 'UTF8'), 'hex')
$$;

create or replace function public.tc_can_write_shared_trip(target_trip_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
      and (role = 'super_admin' or (role = 'trip_editor' and trip_id = target_trip_id))
  )
$$;

revoke all on function public.tc_can_write_shared_trip(text) from public, anon;
grant execute on function public.tc_can_write_shared_trip(text) to authenticated;

alter table public.admin_users enable row level security;
alter table public.trips enable row level security;
create policy v390_admin_read on public.admin_users for select to authenticated using (true);
create policy v390_trip_read on public.trips for select to authenticated using (true);
grant select on public.admin_users, public.trips to authenticated, service_role;

insert into auth.users (id, email, created_at, updated_at)
values ('39039039-0390-4390-8390-390390390390', 'v390-editor@example.invalid', now(), now());
insert into public.admin_users (email, role, trip_id)
values ('v390-editor@example.invalid', 'trip_editor', 'trip-v390');
insert into public.trips (id, title, departure_date, content)
values ('trip-v390', 'V3.9.0 fixture', current_date, '{"days":[1]}'::jsonb);
