import { Calculator, Pencil, Save, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { TripExchangePurchase } from "../types";
import { readExchangePurchases, writeExchangePurchases } from "../storage/exchangeRateStorage";
import { formatForeignAmount, formatRate, formatTwd } from "../utils/currencyFormat";
import { getExchangeSummary } from "../utils/exchangeRate";

const CURRENCIES = ["JPY", "KRW", "USD", "EUR"];
type PurchaseForm = Pick<TripExchangePurchase, "foreignCurrency" | "purchaseDate" | "twdAmount" | "foreignAmount">;
const today = () => new Date().toISOString().slice(0, 10);
const createForm = (currency: string): PurchaseForm => ({ foreignCurrency: CURRENCIES.includes(currency) ? currency : "JPY", purchaseDate: today(), twdAmount: 0, foreignAmount: 0 });
const createId = () => globalThis.crypto?.randomUUID?.() ?? `exchange-${Date.now()}-${Math.random().toString(36).slice(2)}`;

interface ExchangeRatePageProps { tripId: string; defaultForeignCurrency: string; }

export const ExchangeRatePage = ({ tripId, defaultForeignCurrency }: ExchangeRatePageProps) => {
  const initialCurrency = CURRENCIES.includes(defaultForeignCurrency) ? defaultForeignCurrency : "JPY";
  const [purchases, setPurchases] = useState(() => readExchangePurchases(tripId));
  const [selectedCurrency, setSelectedCurrency] = useState(initialCurrency);
  const [form, setForm] = useState<PurchaseForm>(() => createForm(initialCurrency));
  const [editingId, setEditingId] = useState<string | null>(null);
  const [calculatorAmount, setCalculatorAmount] = useState("");
  const summary = useMemo(() => getExchangeSummary(tripId, purchases, selectedCurrency), [purchases, selectedCurrency, tripId]);
  const visiblePurchases = useMemo(() => purchases.filter((item) => item.foreignCurrency === selectedCurrency).sort((a, b) => b.purchaseDate.localeCompare(a.purchaseDate) || b.createdAt.localeCompare(a.createdAt)), [purchases, selectedCurrency]);
  const hasValidForm = form.twdAmount > 0 && form.foreignAmount > 0 && Boolean(form.purchaseDate);
  const persist = (next: TripExchangePurchase[]) => { setPurchases(next); writeExchangePurchases(tripId, next); };
  const resetForm = (currency = selectedCurrency) => { setEditingId(null); setForm(createForm(currency)); };
  const updateForm = <K extends keyof PurchaseForm>(key: K, value: PurchaseForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const handleSave = () => {
    if (!hasValidForm) return;
    const now = new Date().toISOString();
    persist(editingId ? purchases.map((item) => item.id === editingId ? { ...item, ...form, updatedAt: now } : item) : [...purchases, { id: createId(), tripId, ...form, createdAt: now, updatedAt: now }]);
    setSelectedCurrency(form.foreignCurrency); resetForm(form.foreignCurrency);
  };
  const handleEdit = (item: TripExchangePurchase) => { setEditingId(item.id); setSelectedCurrency(item.foreignCurrency); setForm({ foreignCurrency: item.foreignCurrency, purchaseDate: item.purchaseDate, twdAmount: item.twdAmount, foreignAmount: item.foreignAmount }); };
  const handleDelete = (id: string) => { if (window.confirm("確定要刪除這筆換匯紀錄嗎？")) { persist(purchases.filter((item) => item.id !== id)); if (editingId === id) resetForm(); } };
  const calculatorValue = Number(calculatorAmount);

  return <section className="space-y-5">
    <div><p className="text-xs font-bold uppercase tracking-wider text-sky-700">Travel Tool</p><h2 className="text-2xl font-extrabold text-slate-900">外幣換算</h2><p className="mt-1 text-sm leading-relaxed text-slate-500">記錄實際換匯金額，以加權平均匯率估算旅途中的新臺幣花費。</p></div>
    <div className="rounded-xl border border-sky-100 bg-sky-50 p-4"><label className="mb-2 block text-xs font-bold text-sky-900">外幣幣別</label><select value={selectedCurrency} onChange={(event) => { const currency = event.target.value; setSelectedCurrency(currency); if (!editingId) resetForm(currency); }} className="w-full rounded-lg border border-sky-200 bg-white px-3 py-2 text-sm font-bold text-slate-700 outline-none focus:border-sky-500">{CURRENCIES.map((currency) => <option key={currency} value={currency}>{currency}</option>)}</select>{summary ? <div className="mt-4 rounded-lg bg-white p-3 shadow-sm"><p className="text-xs font-bold text-slate-500">目前加權平均匯率</p><p className="mt-1 text-xl font-extrabold text-sky-800">1 {selectedCurrency} = {formatRate(summary.weightedAverageRate)} TWD</p><p className="mt-1 text-xs text-slate-500">累計 {formatTwd(summary.totalTwdAmount)} ÷ {formatForeignAmount(summary.totalForeignAmount, selectedCurrency)}</p></div> : <p className="mt-3 text-sm text-sky-900">尚無有效換匯紀錄，新增後即可計算平均匯率。</p>}</div>
    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-bold text-slate-800">{editingId ? "編輯換匯紀錄" : "新增換匯紀錄"}</h3>{editingId && <button type="button" onClick={() => resetForm()} className="inline-flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-slate-800"><X size={14} />取消編輯</button>}</div><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold text-slate-600">日期<input type="date" value={form.purchaseDate} onChange={(event) => updateForm("purchaseDate", event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-slate-700 outline-none focus:border-sky-500" /></label><label className="text-sm font-semibold text-slate-600">幣別<select value={form.foreignCurrency} onChange={(event) => updateForm("foreignCurrency", event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-slate-700 outline-none focus:border-sky-500">{CURRENCIES.map((currency) => <option key={currency} value={currency}>{currency}</option>)}</select></label><label className="text-sm font-semibold text-slate-600">支付新臺幣<input type="number" min="0" step="1" value={form.twdAmount || ""} onChange={(event) => updateForm("twdAmount", Number(event.target.value))} placeholder="例如 20100" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-slate-700 outline-none focus:border-sky-500" /></label><label className="text-sm font-semibold text-slate-600">取得外幣<input type="number" min="0" step="0.01" value={form.foreignAmount || ""} onChange={(event) => updateForm("foreignAmount", Number(event.target.value))} placeholder="例如 100000" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-slate-700 outline-none focus:border-sky-500" /></label></div><button type="button" disabled={!hasValidForm} onClick={handleSave} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-sky-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-sky-800 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={16} />{editingId ? "儲存變更" : "新增換匯紀錄"}</button></div>
    <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold text-slate-800">{selectedCurrency} 換匯紀錄</h3><span className="text-xs font-semibold text-slate-400">{visiblePurchases.length} 筆</span></div>{visiblePurchases.length === 0 ? <p className="py-5 text-center text-sm text-slate-400">尚無 {selectedCurrency} 換匯紀錄</p> : <div className="space-y-2">{visiblePurchases.map((item) => <article key={item.id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-bold text-slate-800">{item.purchaseDate}</p><p className="mt-1 text-sm text-slate-600">{formatTwd(item.twdAmount)} → {formatForeignAmount(item.foreignAmount, item.foreignCurrency)}</p><p className="mt-1 text-xs text-slate-500">1 {item.foreignCurrency} = {formatRate(item.twdAmount / item.foreignAmount)} TWD</p></div><div className="flex gap-1"><button type="button" onClick={() => handleEdit(item)} aria-label="編輯換匯紀錄" className="rounded-md p-2 text-slate-500 hover:bg-white hover:text-sky-700"><Pencil size={15} /></button><button type="button" onClick={() => handleDelete(item.id)} aria-label="刪除換匯紀錄" className="rounded-md p-2 text-slate-500 hover:bg-white hover:text-rose-700"><Trash2 size={15} /></button></div></div></article>)}</div>}</div>
    <div className="rounded-xl border border-amber-100 bg-amber-50 p-4"><div className="flex items-center gap-2"><Calculator size={18} className="text-amber-700" /><h3 className="font-bold text-amber-950">外幣轉新臺幣</h3></div><p className="mt-1 text-xs leading-relaxed text-amber-800">依目前 {selectedCurrency} 加權平均匯率估算，僅供參考。</p><input type="number" min="0" step="0.01" value={calculatorAmount} onChange={(event) => setCalculatorAmount(event.target.value)} placeholder={`輸入 ${selectedCurrency} 金額`} className="mt-3 w-full rounded-lg border border-amber-200 bg-white px-3 py-2 text-slate-700 outline-none focus:border-amber-500" /><p className="mt-3 text-lg font-extrabold text-amber-900">{summary && calculatorAmount !== "" && Number.isFinite(calculatorValue) && calculatorValue >= 0 ? `${formatForeignAmount(calculatorValue, selectedCurrency)} ≈ ${formatTwd(calculatorValue * summary.weightedAverageRate)}` : "新增換匯紀錄後即可換算"}</p></div>
  </section>;
};
