-- Restore the unmanaged V3.0-era schema prerequisites for clean local builds.
--
-- The earliest tracked migration (20260710101530) historically assumed these
-- objects had been created manually.  Keeping this as a separate, earlier
-- migration preserves the published migration files while making
-- `supabase start` reproducible from an empty local database.

create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'trip_editor')),
  trip_id text not null default '',
  constraint admin_users_normalized_email_check check (
    email = lower(btrim(email)) and position('@' in email) > 1
  )
);

create unique index if not exists admin_users_one_role_per_trip_email
on public.admin_users (email, role, trip_id);

create or replace function public.tc_current_email()
returns text
language sql
stable
set search_path = ''
as $$
  select lower(coalesce(nullif((select auth.jwt()) ->> 'email', ''), ''));
$$;

create or replace function public.tc_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where email = public.tc_current_email() and role = 'super_admin'
  );
$$;

create or replace function public.tc_is_trip_editor(target_trip_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where email = public.tc_current_email()
      and role = 'trip_editor'
      and trip_id = target_trip_id
  );
$$;

create or replace function public.tc_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

-- These tables existed before the repository began tracking migrations.  Later
-- migrations own their security policies and version-specific columns.
create table if not exists public.checklists (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  scope text not null check (scope in ('shared', 'private')),
  owner_user_id uuid null references auth.users(id) on delete cascade,
  title text not null default '確認清單',
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint checklists_scope_owner_check check (
    (scope = 'shared' and owner_user_id is null)
    or (scope = 'private' and owner_user_id is not null)
  )
);

create table if not exists public.checklist_items (
  id uuid primary key default gen_random_uuid(),
  checklist_id uuid not null references public.checklists(id) on delete cascade,
  client_item_id text null,
  label text not null,
  is_checked boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create index if not exists checklist_items_checklist_order
on public.checklist_items (checklist_id, sort_order, created_at);

create table if not exists public.other_info_items (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  client_item_id text null,
  folder_id text not null default '',
  title text not null,
  content text not null default '',
  allowed_roles text[] null,
  sort_order integer not null default 0,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create or replace function public.tc_other_info_role(target_trip_id text)
returns text
language sql
stable
set search_path = ''
as $$
  select case
    when public.tc_is_super_admin() then 'super_admin'
    when public.tc_is_trip_editor(target_trip_id) then 'trip_editor'
    when (select auth.uid()) is not null then 'user'
    else 'guest'
  end;
$$;

create or replace function public.tc_can_edit_other_info(target_trip_id text)
returns boolean
language sql
stable
set search_path = ''
as $$
  select public.tc_is_super_admin()
    or public.tc_is_trip_editor(target_trip_id);
$$;

create table if not exists public.exchange_purchases (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  client_item_id text not null,
  foreign_currency text not null default 'JPY',
  purchase_date date not null default current_date,
  twd_amount numeric(14, 2) not null default 0,
  foreign_amount numeric(18, 4) not null default 0,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trip_id, client_item_id)
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  trip_id text not null,
  title text not null default '',
  amount numeric(14, 2) not null default 0,
  payer text not null default '',
  currency text not null default 'JPY',
  created_at timestamptz not null default now()
);
